services:
  izzup-zitadel:
    restart: 'no'
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "${IZZUP_ZITADEL_MASTERKEY}" --tlsMode external'
    # command: 'start-from-setup --masterkey "${IZZUP_ZITADEL_MASTERKEY}" --tlsMode external'
    environment:
      ZITADEL_DATABASE_POSTGRES_HOST: 172.17.0.1
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: izzup_zitadel
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel_izzup
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: ${IZZUP_ZITADEL_POSTGRES_PASSWORD}
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: ${POSTGRES_PASSWORD}
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      ZITADEL_EXTERNALDOMAIN: 'auth.izzup.com'
      ZITADEL_EXTERNALPORT: 443
      ZITADEL_EXTERNALSECURE: true
      ZITADEL_TLS_ENABLED: false
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROM: 'support@izzup.com'
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROMNAME: 'Izzup Support Team'
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST: 'smtp.titan.email:465'
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_USER: 'support@izzup.com'
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_PASSWORD: 'J-6MZLwSh,E^YdG'
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_TLS: true
      ZITADEL_DEFAULTINSTANCE_DOMAINPOLICY_SMTPSENDERADDRESSMATCHESINSTANCEDOMAIN: false

      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME: 'support@izzup.com'
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD: 'MyComplexP4sswurd!'
      ZITADEL_FIRSTINSTANCE_ORG_NAME: 'Izzup'
    networks:
      - zitadel_auth
    ports:
      - '127.0.0.1:8866:8080'

networks:
  zitadel_auth:
    external: false
    driver: bridge